log_path: "./data/processed/asr/finetune_seq2seq/ipa-whisper-base_20260526_152906/train_log.tsv"
out_dir: "./data/processed/asr/finetune_seq2seq/ipa-whisper-base_20260526_152906/split_seed_42"
x_col: "step"
show: false
