log_path: "./data/processed/asr/finetune/mms-1b-all_20260522_153638/train_log.tsv"
model_id: "mms-1b-all"
out_dir: "./data/processed/asr/finetune/mms-1b-all_20260522_153638/split_seed_42"
x_col: "step"
show: false
