backend: granite
metadata: ./logs/prep/yonghe_qiang/cer90/metadata.csv
audio_root: ~/projects/my-projects/asr-models/language-downloads/yonghe-qiang_01/processed/splits
train_csv: ./logs/prep/yonghe_qiang/cer90/splits/train.csv
dev_csv: ./logs/prep/yonghe_qiang/cer90/splits/dev.csv
test_csv: ./logs/prep/yonghe_qiang/cer90/splits/test.csv
model_id: ibm-granite/granite-4.0-1b-speech
prompt: "<|audio|>can you transcribe the speech into IPA?"
remove_spaces: true # Set to false to train word-boundary spaces
train_seed: 42
batch_size: 1
eval_batch_size: 1
grad_accum_steps: 8
epochs: 25
lr: 0.0002
warmup_steps: 20
bf16: true
lora: true
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules: ["q_proj", "v_proj"]
gradient_checkpointing: true
generation_max_length: 256
out_dir: ~/projects/my-projects/asr-models/language-downloads/yonghe-qiang_01/processed/asr/granite/granite-4.0-1b-speech
