# Model
# model_id_or_path: ~/projects/my-projects/asr-models/language-downloads/yongning-na_01/doreco_yong1270_core_v2.0/processed/asr/xlsr/wav2vec2-xls-r-1b_20260930_122211/best
model_id_or_path: facebook/wav2vec2-xls-r-1b

# null reads the policy saved with the model; true/false explicitly overrides it.
remove_spaces: null

# Data
metadata_delimiter: ","
metadata: ./logs/prep/comparison/20260928_132210/yongning_na/full/metadata.csv
utt_root: ~/projects/my-projects/asr-models/language-downloads/yongning-na_01/doreco_yong1270_core_v2.0/processed/splits/comparison/yongning_na/full

# Output
out_dir: ~/projects/my-projects/asr-models/language-downloads/yongning-na_01/doreco_yong1270_core_v2.0/inference

# LM (optional)
lm_path: null
# lm_path: "~/projects/my-projects/asr-models/language-downloads/yongning-na_01/processed/lm/<run>/lm-yq.binary"
# lm_weight: 0.5
# beam_width: 50
