# Model
model_id_or_path: "./data/processed/asr/finetune/mms-1b-all_20260529_161500/best"

# Data
metadata_delimiter: ","
# metadata: "./data/processed/metadata.csv"
metadata: "./data/processed/splits/test.csv"
utt_root: "./data/processed"

# Output
out_dir: "./data/processed/asr/finetune/mms-1b-all_20260529_161500/"
# out_dir: "./data/processed/metadata_rated.csv"

# LM (optional)
lm_path: ./yq.bin
lm_weight: 0.5
beam_width: 50
