# Model
model_id_or_path: "./data/processed/asr/finetune_seq2seq/ipa-whisper-base_20260526_152906/best"

# Data
metadata_delimiter: ","
metadata: "./data/processed/splits_cer90/test.csv"
utt_root: "./data/processed"

# Output
out_dir: "./data/processed/asr/finetune_seq2seq/ipa-whisper-base_20260526_152906/split_seed_42"

# LM (optional)
# lm_path: null
# lm_weight: 0.5
# beam_width: 50
